#!/usr/bin/env python
from cloudlaunchinstance import CloudLaunchInstance
from allproviderutil import *
from constants import *
import os
import argparse

parser = argparse.ArgumentParser(description='susecloudlaunch')
# Add argument which will show all created environments across CSP's
parser.add_argument(
    "--created",
    help="Show all created environments", action="store_true")
args = parser.parse_args()
if args.created:
    # Clear screen
    os.system('clear')
    for provider in PROVIDERS:
        print('\033[0;32m' + provider.upper() + '\033[0m')
        print(*get_terraform_project_dirs(provider), sep='\n')
        print()

else:
    instance = CloudLaunchInstance("new-instance")
    # Clear screen
    os.system('clear')
    instance.user_interface()
